# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Frederick Morlock
email: me@freddy.us
description: Tinkerer, Researcher, Programmer.
long_description: >-
  Computer Scientist, Mathematician, and Programmer with a passion for open-source and open-science.
  I have been tinkering, coding, and constantly curious for over 15 years, with my lifelong pursuit of knowledge as the bedrock of my being.
  My research primarily lies in Machine Learning Theory, but my interests span many fields connected to mathematics and computing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://freddy.us" # the base hostname & protocol for your site, e.g. http://example.com
repository: FrederickGeek8/freddy.us
author: Frederick Morlock
resume: "https://drive.google.com/file/d/1l9VKO37-7co5hnvBsZ1SueVV1E4vsLR5/view?usp=sharing"

socials:
  googlescholar: "https://scholar.google.com/citations?hl=en&user=7qxBxa4AAAAJ&view_op=list_works&sortby=pubdate"
  mastodon: "https://social.nerd.net/@fooderick"
  mastodon_handle: "@fooderick@nerd.net"
  goodreads: "https://www.goodreads.com/frederickgeek8"
  github: "https://github.com/FrederickGeek8"
  letterboxd: "https://letterboxd.com/frederickgeek8/"
  linkedin: "https://www.linkedin.com/in/frederickmorlock"
  bluesky: "https://bsky.app/profile/freddy.us"

# Comment system information
comments:
  backend: "rest" # must be rest or sqlite
  fetch_api: "https://comments.freddy.us/api/get_comments"
  post_api: "https://comments.freddy.us/post_comment"

# Build settings
highligher: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: [3, 4]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-redirect-from
  - comment_generator
  # - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - TODO.md
  - .prettierrc
  - .gitignore
  - .gitmodules
  - .sass-cache
  - vendor
  - _plugins

defaults:
  - scope:
      path: "assets/**"
    values:
      sitemap: false
  - scope:
      path: "blog/categories/*"
    values:
      sitemap: false
  - scope:
      path: "blog/tags/*"
    values:
      sitemap: false
  - scope:
      path: "_redirects/*"
    values:
      sitemap: false

collections:
  microposts:
    category: microposts
    permalink: /blog/micros/:title/
    output: true
  redirects:
    output: true

feed:
  excerpt_only: true
  read_more_text: 'Read the full blog post &#x2192;'
  tags: true
  categories:
    - CS
    - Personal
    - Tutorials
    - Libraries
    - meta
    - Math
  collections:
    microposts:
      # Create a feed with and without
      xinclude: true

sass:
  style: compressed

blog_root: "/blog"

# Custom stuff
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Resume/CV
    url: /resume/
  - title: My Bookshelf
    url: /bookshelf/
  - title: Blog
    url: /blog/
  - title: Contact Me
    url: /contact/

# Post permalink format
permalink: /blog/posts/:title/
# permalink: /blog/:categories/:year/:month/:day/:title/
# permalink: /blog/posts/:year/:month/:day/:title/

webmentions:
  username: freddy.us
  collections:
    - microposts
  js: false
  pause_lookups: true
  bad_uri_policy:
    blacklist:
      - "^https://github.com/"
      - "^https://hub.docker.com/"
      - "^https://a.co/"
      - "^https://freddy.us/"
      - "^https://en.wikipedia.org/"
      - "^https://developer.mozilla.org/"
      - "^https://rclone.org/"
      - "^https://www.realvnc.com/"
      - "^https://brew.sh/"
      - "^https://creativecommons.org/"
      - "^https://social.nerd.net/"
      - "^https://noscript.net/"
      - "^https://www.11ty.dev/"
      - "^https://opensource.org/"
      - "^https://hinaleaimaging.com"
      - "^https://git.gammaspectra.live/"
      - "^https://www.raspberrypi.org"
