# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Frederick Morlock
email: me@freddy.us
description: Researching the boundaries of CS & Math 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://freddy.us" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FrederickGeek8
repository: FrederickGeek8/freddy.us
author: Frederick Morlock
resume: 'https://drive.google.com/file/d/11o0st1t7VJx8rg1RcgJzFW3q0JSlgz3C/view?usp=sharing'

# Build settings
highligher: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-redirect-from
  # - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - TODO.md
  - .prettierrc
  - .gitignore
  - .gitmodules
  - .sass-cache

defaults:
  - scope:
      path: "assets/**"
    values:
      sitemap: false
  - scope:
      path: "blog/categories/*"
    values:
      sitemap: false
  - scope:
      path: "blog/tags/*"
    values:
      sitemap: false

feed:
  excerpt_only: true
  tags: true
  categories:
    - CS
    - Personal
    - Tutorials
    - Libraries

sass:
  style: compressed

blog_root: '/blog'

# Custom stuff
navigation:
  - title: Home
    url: /
  - title: My Bookshelf
    url: /bookshelf/
  - title: Blog
    url: /blog/

# Post permalink format
# permalink: /blog/:categories/:year/:month/:day/:title/
permalink: /blog/posts/:year/:month/:day/:title/
