# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Frederick Morlock
email: FrederickGeek8@gmail.com
description: ># Frederick Morlock's personal blog and portfolio.Honors Mathematics
 major at NYU Shanghai. Avid programmer for over 11 years. Versed in Web, Mobile,
 and Desktop Software Development. Devote tinkerer and social activist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://freddy.us" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FrederickGeek8
github_username:  FrederickGeek8

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  style: compressed
  sass_dir: assets/css
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
